---
title: "Pull Request Checklist"
---

Make sure all of these are ticked before you submit your pull request for review:

::: {style="background-color: #00a33b;
            color: white;
            padding: 1em;
            border-radius: 10px;"}
Make sure you tick off this **checklist** before submitting a pull request:

-   Git

    <input type="checkbox"> Are you merging into the appropriate branch (usually *dev*)?

-   Admin

    <input type="checkbox"> Have you provided the reviewer with a good description of what the code is meant to do in your pull request?

    <input type="checkbox"> Have you updated the relevant [quality assurance logs](https://defra.sharepoint.com/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/Forms/AllItems.aspx?csf=1&web=1&e=77PIAm&xsdata=MDV8MDF8fGVmMDUxZTI0M2UzMDQyMGQxYjdkMDhkYmNlZjdmNmVhfDc3MGEyNDUwMDIyNzRjNjI5MGM3NGUzODUzN2YxMTAyfDB8MHw2MzgzMzEzMzY1OTc4Mzg3MTd8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPakZoTVdRd056STNZelExTXpSaU5UVmhOVEJsWlRNNVpHSTFOVGc1WWpneFFIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOamszTlRNMk9EVTVORGsxfDA0YjRiYjU2MzdhMzRjYjUxYjdkMDhkYmNlZjdmNmVhfGNmYzQ5YjQ2MGE1ODQzZDc5YzdkYmVlY2QxYjBhYzY4&sdata=YVFjcG55cWNSNnk1cmlDSk9xNzhNNURzd0tCRnhZNzJKZUFSbG52OVZMTT0%3D&ovuser=770a2450%2D0227%2D4c62%2D90c7%2D4e38537f1102%2CJacob%2EBillingham%40defra%2Egov%2Euk&OR=Teams%2DHL&CT=1697538108978&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA5MDExMjI3OCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=22c09b0c%2D5d1a%2D4bfc%2D9011%2D4b821c8b4eb1&FolderCTID=0x0120009DD0451A50BCD14598E383179B1663D1&id=%2Fteams%2FTeam1478%2FExtended%20Producer%20Responsibility%20for%20Packaging%2F15%20Fees%20and%20Payments%20Calculator%20%28FPC%29%2F18%20Module%20B1%20%2D%20LA%20FNCs%2F04%20Bottom%2Dup%20Modelling%2FQA%20Logs&viewid=ec0dda87%2Dc649%2D45d1%2Da9f9%2D150ad0e349b4)?

    Your role is 'doer' and as such you need to fill out the relevant sections in the 'Cover', 'Data Log', 'Assumptions Log' and 'Outputs' tabs. Note any new data uploaded to S3 should be logged in our [S3 Data Log](https://defra.sharepoint.com/:x:/r/teams/Team1478/_layouts/15/Doc.aspx?sourcedoc=%7B2FCDCE89-3F0D-41DD-B451-CB0D77D8DA26%7D&file=Data%20Log%20Ranch_479.xlsx&action=default&mobileredirect=true) and the information can then be copied across to the QA log data tab.

    <input type="checkbox"> Have you added any issues identified to the Jira backlog?

-   Coding Standards

    <input type="checkbox"> Have you linted your code to ensure it complies with the style guide?

    <input type="checkbox"> Is your code's logic clear and free of unnecessary complexity?

    <input type="checkbox"> Have you commented to explain whenever logic is not obvious?

    <input type="checkbox"> Are variable names in plain English and informative?

    <input type="checkbox"> Are the outputs reproducible i.e. will the code work the same on someone else's machine?

-   Modularisation

    <input type="checkbox"> Are individual pieces of logic, i.e. that carry out one specific task, written as functions?

    <input type="checkbox"> Does one main analysis script source and run functions from subscripts?

    <input type="checkbox"> Is repetition in the code minimalised? For example, by moving reusable code into functions or classes.

-   Project Structure

    <input type="checkbox"> Is your code in the right repo and folder within that repo? See [repo structure](codingrepositorystructure.html) if unsure.

    <input type="checkbox"> Are your imports done from the '*imports.R*' file?
    
    <input type="checkbox"> Are your functions sourced from the '*source.R*' file?

    <input type="checkbox"> Are your outputs written to the right place in S3?

-   Documentation

    <input type="checkbox"> Have you updated the README files with any changes relevant to your code?

-   For future use:

    <input type="checkbox"> Have you documented all assumptions using the [assumptions package](https://assumptions.readthedocs.io/en/latest/index.html)?

    <input type="checkbox"> Does your code have adequate unit tests? Are these run automatically using git hooks?

    <input type="checkbox"> Does your code pass existing unit tests?
:::