---
title: "Code Review Checklist"
---

Make sure all of these are ticked before you approve a pull request assigned to you:

<div style="background-color: #00a33b;
            color: white;
            padding: 1em;
            border-radius: 10px;">

Make sure you tick off this **checklist** before approving a code review:
    
-   Git
    
    <input type="checkbox"> Are they merging into the appropriate branch (usually *dev*)? 
    
-   Admin

    <input type="checkbox"> Have they provided you with a good description of what the code is meant to do in the pull request?

    <input type="checkbox"> Have they updated the relevant [quality assurance logs](https://defra.sharepoint.com/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/Forms/AllItems.aspx?csf=1&web=1&e=77PIAm&xsdata=MDV8MDF8fGVmMDUxZTI0M2UzMDQyMGQxYjdkMDhkYmNlZjdmNmVhfDc3MGEyNDUwMDIyNzRjNjI5MGM3NGUzODUzN2YxMTAyfDB8MHw2MzgzMzEzMzY1OTc4Mzg3MTd8VW5rbm93bnxWR1ZoYlhOVFpXTjFjbWwwZVZObGNuWnBZMlY4ZXlKV0lqb2lNQzR3TGpBd01EQWlMQ0pRSWpvaVYybHVNeklpTENKQlRpSTZJazkwYUdWeUlpd2lWMVFpT2pFeGZRPT18MXxMMk5vWVhSekx6RTVPakZoTVdRd056STNZelExTXpSaU5UVmhOVEJsWlRNNVpHSTFOVGc1WWpneFFIUm9jbVZoWkM1Mk1pOXRaWE56WVdkbGN5OHhOamszTlRNMk9EVTVORGsxfDA0YjRiYjU2MzdhMzRjYjUxYjdkMDhkYmNlZjdmNmVhfGNmYzQ5YjQ2MGE1ODQzZDc5YzdkYmVlY2QxYjBhYzY4&sdata=YVFjcG55cWNSNnk1cmlDSk9xNzhNNURzd0tCRnhZNzJKZUFSbG52OVZMTT0%3D&ovuser=770a2450%2D0227%2D4c62%2D90c7%2D4e38537f1102%2CJacob%2EBillingham%40defra%2Egov%2Euk&OR=Teams%2DHL&CT=1697538108978&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA5MDExMjI3OCIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&cid=22c09b0c%2D5d1a%2D4bfc%2D9011%2D4b821c8b4eb1&FolderCTID=0x0120009DD0451A50BCD14598E383179B1663D1&id=%2Fteams%2FTeam1478%2FExtended%20Producer%20Responsibility%20for%20Packaging%2F15%20Fees%20and%20Payments%20Calculator%20%28FPC%29%2F18%20Module%20B1%20%2D%20LA%20FNCs%2F04%20Bottom%2Dup%20Modelling%2FQA%20Logs&viewid=ec0dda87%2Dc649%2D45d1%2Da9f9%2D150ad0e349b4)?
        
    Your role is 'checker' and as such you should fill out the relevant sections in the 'Data Log', 'QA- Verification' and 'Outputs' tabs.

-   Purpose
    
    <input type="checkbox"> Does the code do what is set out in the ticket?
    
    <input type="checkbox"> Does the code run succesfully and behave the same for you?
    
-   Coding Standards

    <input type="checkbox"> Have they linted their code to ensure it complies with the style guide?

    <input type="checkbox"> Is their code's logic clear and free of unnecessary complexity?

    <input type="checkbox"> Have they commented to explain whenever logic is not obvious?
    
    <input type="checkbox"> Are variable names in plain English and informative?
    
-   Modularisation

    <input type="checkbox"> Are individual pieces of logic, i.e. that carry out one specific task, written as functions?
    
    <input type="checkbox"> Does one main analysis script source and run functions from subscripts? 
    
    <input type="checkbox"> Are similar functions contained in the same subscripts?
    
    <input type="checkbox"> Is repetition in the code minimalised? For example, by moving reusable code into functions or classes.

-   Project Structure
    
    <input type="checkbox"> Is their code in the right repo and folder within that repo? See [repo structure](codingrepositorystructure.html) if unsure.
    
    <input type="checkbox"> Are their imports done from the '*imports.R*' file?
    
    <input type="checkbox"> Are their functions sourced from the '*source.R*' file?

    <input type="checkbox"> Are their outputs written to the right place in S3?
    
-   Documentation

    <input type="checkbox"> Have they updated the README files with any changes relevant to their code?

-   For future use:

    <input type="checkbox"> Have they documented all assumptions using the [assumptions package](https://assumptions.readthedocs.io/en/latest/index.html)?

    <input type="checkbox"> Does their code have adequate unit tests? Are these run automatically using git hooks?
    
    <input type="checkbox"> Does their code pass existing unit tests?
    
</div>