---
title: "Coding Environment"
---

We use Defra's **Scientific Coding Environment** which allows us to write and run code on Amazon Web Service's EC2 virtual machines, and store our data using Amazon Web Services S3. Speak to the SCE admins (Ope and Jake as of September 2023) if you are not set up on the SCE. Guidance documents can be found at on [Sharepoint](https://defra.sharepoint.com/teams/Team1478/Extended%20Producer%20Responsibility%20for%20Packaging/Forms/AllItems.aspx?OR=Teams%2DHL&CT=1684860172742&clickparams=eyJBcHBOYW1lIjoiVGVhbXMtRGVza3RvcCIsIkFwcFZlcnNpb24iOiIyNy8yMzA0MDIwMjcwNSIsIkhhc0ZlZGVyYXRlZFVzZXIiOmZhbHNlfQ%3D%3D&id=%2Fteams%2FTeam1478%2FExtended%20Producer%20Responsibility%20for%20Packaging%2F15%20Fees%20and%20Payments%20Calculator%20%28FPC%29%2F18%20Module%20B1%20%2D%20LA%20FNCs%2F14%20Module%20B1%20Admin%2FCoding%20Environment&viewid=ec0dda87%2Dc649%2D45d1%2Da9f9%2D150ad0e349b4).

# S3

S3 is accessed through the [AWS console](https://int-sce-network.awsapps.com/console). When we upload, modify or delete data on S3, this must be recorded in the [Data Log](https://defra.sharepoint.com/:x:/r/teams/Team1478/_layouts/15/Doc.aspx?sourcedoc=%7B2FCDCE89-3F0D-41DD-B451-CB0D77D8DA26%7D&file=Data%20Log%20Ranch_479.xlsx&action=default&mobileredirect=true).

**All binned waste data** should be stored in the 'moduleB2' folder at: *s3://s3-ranch-043/moduleB2/*.

Scripts for reading and writing to AWS can be found in the [useful scripts repo](https://github.com/Defra-pEPR-Modelling-Team/useful_scripts/blob/main/AWS%20to%20R.Rmd). Here is an example of **reading** an **Excel** file:
```{r AWS read, eval = FALSE}
excel_data <- aws.s3::s3read_using(
  FUN = openxlsx::read.xlsx,
  object = "test_folder/test_data.xlsx", # this file exists, but replace with your own filepath
  sheet="Sheet1",
  fillMergedCells = TRUE,
  bucket = "s3-ranch-043")
```

# R Studio

We can use [R Studio on our virtual machine](http://ranch-479.int.sce.network/rstudio/). This is available 8am - 8pm daily. 

# Github

We use Github for version control, collaboration and code reviews. Our [organisation homepage](https://github.com/Defra-pEPR-Modelling-Team) has information on how to do all of these.