---
title: "Team Members"
---

[comment]: <> (Have this data in an excel file that I can then download and write a script to produce this table?)

| Name | Areas of Work | Location | Working Pattern | Preferred Communication Method | Tips for Working Together | 
|---|---|---|---|---|---|
| Jake Billingham | Team Lead | Usually London office Mon - Thur, at home in North London on Friday | Mon - Fri, 9:30 - 5:30 | In person > Teams message > Email (but use email for anything we may need a record of) | Don't put meetings over Wednesday table tennis! |
| Ope Ojo  | Coding Expert | London office Wednesdays and either Tuesday or Thursday | Mon - Fri, 9:30 - 5:30 | Whichever is best for the context |  |  |
| Jo Keegan | Readiness Lead |  Working from home in Staffordshire | Mon - Thu, 8 - 5:30/6 | Whichever is best for the context |  |
| Clare Watson | Policy Lead | Bristol office 4 days a week | Mon - Fri, 9:30 - 5:30  | Whichever is best for the context |  |
| Bim Chaloner | ? | ? |  ? | ? | ? |

**New joiners:** Let Jake know and he can add your details!

