---
title: "How We Work"
---

When working on model the we use the following methodology:

## Weekly

| | Monday | Tuesday | Wednesday | Thursday | Friday |
|---|:---:|:---:|:---:|:---:|:---:|
| **Meeting** | Allocating Tickets (11am, 1 hour) | Check In (9:20am, 10 mins) | Check In (9:20am, 10 mins) | Ticket Check (10:00am, 1 hour) | Demos (3:30pm, 30 mins) |
| **Purpose** | Deciding which tickets we want to complete this week and allocating among us. | Updates, solving problems. | Updates, solving problems. | Helping with any tickets that have not been submitted for review. Attendance only required if you have open tickets. | Reviewing completed tickets. Demonstrating working code and a look forward to next week. |

This means you will have Monday, Tuesday and Wednesday to work on any tickets assigned to you on a Monday. If you think the ticket will take you more than 3 days you should **raise it on Monday.** 

Thursday and Friday are then for your reviewer to do their review, and you to make any changes requested before merging!

We manage tasks for each sprint on 
-   [Module B1 Jira board](https://eaflood.atlassian.net/jira/software/projects/B1/boards/1483) and
-   [Module B2 Jira board](https://eaflood.atlassian.net/jira/software/projects/B2/boards/1486).

## Longer Term

Several of these sprints will form each **model building cycle**. These will be bookended by extended kickoff and review meetings as shown below:

||||||||
|---|:---:|:---:|:---:|:---:|:---:|:---:|
| **Activity** | Kickoff Meeting (1 hr) | Sprint 1 | Sprint 2 | Sprint 3 | ... | Review Meeting (1 hr) |
| **Purpose** | What do we want to achieve this cycle? ||||| Did we achieve our goals? What lessons did we learn? Review our ticket backlog. |

