---
title: "Our Work"
---

The Module B2 Binned Waste team is responsible for developing a model to estimate local authorities' costs of collecting and disposing of packaging placed in street bins. 

Producers will then be required to pay these costs which will incentivise them to reduce packaging waste and make packaging more recyclable.

This brings many benefits including greater resource efficiency, reduced pollution and reduced carbon emissions, supporting nature and combatting climate change.

The [plan on a page](https://defra.sharepoint.com/:p:/r/teams/Team1478/_layouts/15/Doc.aspx?sourcedoc=%7B14C0DDD3-867B-4EA2-BC52-CB7999CE1165%7D&file=04%20Binned_Waste_Programme_POAP_LIVE.pptx&action=edit&mobileredirect=true&PreviousSessionID=ebc4a168-d4bd-f4a1-e658-81828bc9da9f) gives timelines and milestones for developing this model.

# Meetings

These guidelines for meetings are endorsed by our senior leadership so please use them: 

1.	All employees are empowered to block out time in calendars free of meetings and this is respected. 
2.	All colleagues should avoid setting up meetings where possible if time has been blocked out. 
3.	We will block out the Defra lunch hour (12:30-1:30pm) in all R&W employees.
4.	Before producing your invite consider if the whole team is required or if a representative would work with notes to take away to present to their team.
5.	All meetings have a clear agenda and purpose, circulated ahead of the meeting to allow individuals to prepare and contribute effectively – and will inform who is best placed to attend.
6.	Meetings should typically be no longer than 50 minutes, which allows 10 minutes comfort between meetings. Meetings that are longer than 50 minutes should include a 10-minute comfort break. 
7.	Avoid multi-tasking and working on other documents allowing people to be present. 
8.	Using calendars correctly - accepting and declining meetings (select to send a response this will update tracking) - tracking can then be seen and it can be   determined if the meeting should go ahead.
9.	A short readout and key points should be cascaded to relevant teams asap after the meeting.
